/*
 * Evan Robertson
 * December 18th 2018
 * Managing data files into a program
 */

package data;
import java.io.*;

/**
 *
 * @author evrob0095
 */
public class data extends javax.swing.JFrame {

    /**
     * Creates new form data
     */
    public data() {
        initComponents();
    }
    File dataFile = new File("students");
    FileReader in;
    BufferedReader readFile;
    String [] students = new String[4];
    int [] marks = new int[4];
    String score;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mark4 = new javax.swing.JTextField();
        mark1 = new javax.swing.JTextField();
        mark2 = new javax.swing.JTextField();
        mark3 = new javax.swing.JTextField();
        name4 = new javax.swing.JLabel();
        average = new javax.swing.JLabel();
        averageButton = new javax.swing.JButton();
        subtitle = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        nameButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        averageLabel = new javax.swing.JLabel();
        sMark4 = new javax.swing.JLabel();
        studentMarks = new javax.swing.JLabel();
        sMark1 = new javax.swing.JLabel();
        sMark2 = new javax.swing.JLabel();
        sMark3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(mark4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 40, -1));
        jPanel1.add(mark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 40, -1));
        jPanel1.add(mark2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 40, -1));
        jPanel1.add(mark3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 40, -1));

        name4.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        name4.setText("********");
        jPanel1.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        average.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        average.setText("0%");
        jPanel1.add(average, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        averageButton.setText("Calculate Average");
        averageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                averageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(averageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 140, -1));

        subtitle.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        subtitle.setText("Enter marks of students");
        jPanel1.add(subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        name1.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        name1.setText("********");
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 20));

        name2.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        name2.setText("********");
        jPanel1.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        name3.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        name3.setText("********");
        jPanel1.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        nameButton.setText("Get Names");
        nameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        title.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        title.setText("Marking  Data");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        averageLabel.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        averageLabel.setText("Class Average");
        jPanel1.add(averageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        sMark4.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        sMark4.setText("...");
        jPanel1.add(sMark4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 150, -1));

        studentMarks.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        studentMarks.setText("Student Marks");
        jPanel1.add(studentMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        sMark1.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        sMark1.setText("...");
        jPanel1.add(sMark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 150, -1));

        sMark2.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        sMark2.setText("...");
        jPanel1.add(sMark2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 160, -1));

        sMark3.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        sMark3.setText("...");
        jPanel1.add(sMark3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void averageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_averageButtonActionPerformed
        
        //Get marks and put into an array
        marks[0] = Integer.parseInt(mark1.getText());
        marks[1] = Integer.parseInt(mark2.getText());
        marks[2] = Integer.parseInt(mark3.getText());
        marks[3] = Integer.parseInt(mark4.getText());
        
        //Calculate average and print to screen
        int total = (marks[0] + marks[1] + marks[2] + marks[3])/4;
        average.setText(total + "%");
        
        sMark1.setText(students[0] + " got a score of " + marks[0]);
        sMark2.setText(students[1] + " got a score of " + marks[1]);
        sMark3.setText(students[2] + " got a score of " + marks[2]);
        sMark4.setText(students[3] + " got a score of " + marks[3]);
        
    }//GEN-LAST:event_averageButtonActionPerformed

    private void nameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameButtonActionPerformed
        try {
            //Read file and get students names, put in array
            in = new FileReader(dataFile);
            readFile = new BufferedReader(in);
            for (int i = 0; i < 4; i++) {
                students[i] = readFile.readLine();
            } 
            name1.setText(students[0]);
            name2.setText(students[1]);  
            name3.setText(students[2]);  
            name4.setText(students[3]);  

        }
    catch (FileNotFoundException e) {
        System.out.println("File Not Found" + e);
        }
    catch (IOException e) {
        System.out.println("Problem reading file" + e);
        }
    }//GEN-LAST:event_nameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel average;
    private javax.swing.JButton averageButton;
    private javax.swing.JLabel averageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mark1;
    private javax.swing.JTextField mark2;
    private javax.swing.JTextField mark3;
    private javax.swing.JTextField mark4;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JButton nameButton;
    private javax.swing.JLabel sMark1;
    private javax.swing.JLabel sMark2;
    private javax.swing.JLabel sMark3;
    private javax.swing.JLabel sMark4;
    private javax.swing.JLabel studentMarks;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
